change every double quote to single
Rowin206/DatingApp pull request #17
Opened 2019-04-02 12:49 UTC by Rowin206

2019-04-02 12:52 UTC, Rowin206 commented
Well, I was thinking what was more nice to use, single or double. First we agreed to use single, but after making the change, I saw things like double quotes in package.json and every other json files. You can't use single, because it's not allowed. Isn't it nicer to use still double instead of single? Because json used double as well.

2019-04-02 18:28 UTC, RooyyDoe requested changes
* Maybe change up the double quotes at the CSS to be even more consistent?
* In the file 'add.js' you still have double quotes on line 6

But next to this two it looks fine! :)

2019-04-05 10:09 UTC, Rowin206 commented
@RooyyDoe Thanks for the feedback, I changed the two things you told me. So it is ready to merge, but if you can see there is a conflict. Would you like to solve that conflict ? Or do you want me to solve it.

2019-04-05 13:54 UTC, RooyyDoe approved these changes

2019-04-05 14:13 UTC, merged